'use client';

import Link from 'next/link';
import { Activity, ArrowUpRight, BarChart3, Bell, Clapperboard, CreditCard, ShieldCheck, Users, UserRoundCheck } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { api, apiError } from '@/lib/api';
import { formatNumber } from '@/lib/utils';
import { ErrorState, LoadingState, PageHeader, StatCard, StatusBadge } from '@/components/ui';
import { quickLinks } from '@/lib/navigation';

export default function DashboardPage() {
  const query = useQuery({ queryKey: ['dashboard'], queryFn: async () => (await api.get('/reports/dashboard')).data });
  const notification = useQuery({ queryKey: ['latest-notification'], queryFn: async () => (await api.get('/notifications/latest')).data });
  if (query.isLoading) return <LoadingState label="Preparing your operations overview" />;
  if (query.isError) return <ErrorState message={apiError(query.error)} onRetry={() => query.refetch()} />;
  const data = query.data ?? {};
  return <div><PageHeader eyebrow="Today at a glance" title="Good morning, admin" description="A focused view of your audience, library, access and account health." actions={<Link href="/analytics" className="btn-secondary"><BarChart3 size={16} /> View reports</Link>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total users" value={formatNumber(data.users)} note={`${formatNumber(data.activeUsers)} active accounts`} icon={Users} tone="teal" /><StatCard label="Library" value={formatNumber(data.episodes)} note={`${formatNumber(data.dramas)} dramas, ${formatNumber(data.seasons)} seasons`} icon={Clapperboard} tone="brand" /><StatCard label="Active subscriptions" value={formatNumber(data.activeSubscriptions)} note={`${formatNumber(data.pendingSubscriptionRequests)} requests waiting`} icon={CreditCard} tone="gold" /><StatCard label="Video views" value={formatNumber(data.views)} note={`${formatNumber(data.unreadMessages)} unread messages`} icon={Activity} tone="slate" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className="surface p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">Frequent actions</div><h3 className="mt-2 text-lg font-bold">Keep the platform moving</h3></div><ShieldCheck className="text-teal" size={20} /></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{quickLinks.map(({ href, label, icon: Icon }) => <Link href={href} key={href} className="group flex items-center gap-3 border border-line p-4 transition hover:border-teal/40 hover:bg-teal/[0.03]"><span className="flex h-9 w-9 items-center justify-center bg-slate-100 text-slate-600 group-hover:bg-teal/10 group-hover:text-teal"><Icon size={17} /></span><span className="flex-1 text-sm font-semibold">{label}</span><ArrowUpRight size={15} className="text-slate-400" /></Link>)}</div></section><section className="surface p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">Latest notice</div><h3 className="mt-2 text-lg font-bold">Team broadcast</h3></div><Bell size={20} className="text-brand" /></div>{notification.data ? <div className="mt-6 border-l-2 border-brand pl-4"><div className="text-base font-semibold">{notification.data.title}</div><p className="mt-2 text-sm leading-6 text-slate-500">{notification.data.message}</p><div className="mt-4"><StatusBadge value="active" /></div></div> : <p className="mt-6 text-sm text-slate-500">No broadcast has been published yet.</p>}<div className="mt-8 border-t border-line pt-5"><Link href="/security" className="flex items-center gap-3 text-sm font-semibold text-ink hover:text-brand"><UserRoundCheck size={17} className="text-teal" /> Review account and security events <ArrowUpRight size={14} className="ml-auto" /></Link></div></section></div></div>;
}
