import { AlertCircle, CheckCircle2, Loader2, SearchX } from 'lucide-react';
import { cn } from '@/lib/utils';

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: React.ReactNode }) {
  return <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div>{eyebrow && <div className="eyebrow mb-2">{eyebrow}</div>}<h2 className="text-2xl font-bold tracking-tight text-ink md:text-3xl">{title}</h2>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p>}</div>{actions && <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>}</div>;
}

export function StatCard({ label, value, note, tone = 'brand', icon: Icon }: { label: string; value: string | number; note?: string; tone?: 'brand' | 'teal' | 'gold' | 'slate'; icon: React.ComponentType<{ size?: number }> }) {
  const colors = { brand: 'bg-brand/10 text-brand', teal: 'bg-teal/10 text-teal', gold: 'bg-gold/10 text-gold', slate: 'bg-slate-100 text-slate-600' };
  return <div className="surface p-5"><div className="flex items-start justify-between gap-3"><div><div className="eyebrow">{label}</div><div className="mt-3 text-3xl font-bold tracking-tight text-ink">{value}</div>{note && <div className="mt-2 text-xs text-slate-500">{note}</div>}</div><div className={cn('flex h-10 w-10 items-center justify-center', colors[tone])}><Icon size={19} /></div></div></div>;
}

export function LoadingState({ label = 'Loading data' }: { label?: string }) { return <div className="surface flex min-h-[220px] items-center justify-center gap-3 text-sm text-slate-500"><Loader2 className="animate-spin text-teal" size={20} />{label}</div>; }
export function EmptyState({ title = 'Nothing here yet', description = 'New records will appear here when they are created.', action }: { title?: string; description?: string; action?: React.ReactNode }) { return <div className="surface flex min-h-[220px] flex-col items-center justify-center px-6 text-center"><SearchX size={28} className="mb-3 text-slate-300" /><div className="font-semibold text-ink">{title}</div><p className="mt-1 max-w-sm text-sm text-slate-500">{description}</p>{action && <div className="mt-4">{action}</div>}</div>; }
export function ErrorState({ message = 'Unable to load this section.', onRetry }: { message?: string; onRetry?: () => void }) { return <div className="surface flex min-h-[220px] flex-col items-center justify-center px-6 text-center"><AlertCircle size={28} className="mb-3 text-red-400" /><div className="font-semibold text-ink">Something went wrong</div><p className="mt-1 max-w-sm text-sm text-slate-500">{message}</p>{onRetry && <button className="btn-secondary mt-4" onClick={onRetry}>Try again</button>}</div>; }
export function StatusBadge({ value }: { value?: string | boolean | null }) { const normalized = String(value ?? 'unknown').toLowerCase(); const positive = ['active', 'approved', 'published', 'confirmed', 'read', 'visible', 'true'].includes(normalized); const negative = ['disabled', 'rejected', 'archived', 'revoked', 'blocked', 'hidden', 'false'].includes(normalized); return <span className={cn('badge', positive && 'border-teal/20 bg-teal/10 text-teal', negative && 'border-red-200 bg-red-50 text-red-700', !positive && !negative && 'border-slate-200 bg-slate-100 text-slate-600')}>{normalized.replaceAll('_', ' ')}</span>; }
export function Toast({ message, kind = 'success' }: { message: string; kind?: 'success' | 'error' }) { return <div className={cn('fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-2 border bg-white px-4 py-3 text-sm font-semibold shadow-xl', kind === 'success' ? 'border-teal/30 text-teal' : 'border-red-200 text-red-700')}>{kind === 'success' ? <CheckCircle2 size={17} /> : <AlertCircle size={17} />}{message}</div>; }
